config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/projects')
  resources :projects
  get '/biography', to: 'biography#index', as: 'biography'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/biography_controller.rb
class BiographyController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/biography/index.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Quem é Caroline?</h1>
        <p class="lead text-muted">Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing.</p>
    </div>
</section>

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <p class="lead">
                Pode ser que sim, pode ser que não, só depende do ponto de vista.
            </p>

            <p>Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Venusaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Charmander Lorem ipsum dolor sit amet, consectetur adipiscing elit. Charmeleon Lorem ipsum dolor sit amet, consectetur adipiscing elit. Charizard Lorem ipsum dolor sit amet, consectetur adipiscing elit. Squirtle Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
            <p>Alakazam Lorem ipsum dolor sit amet, consectetur adipiscing elit. Machop Lorem ipsum dolor sit amet, consectetur adipiscing elit. Machoke Lorem ipsum dolor sit amet, consectetur adipiscing elit. Machamp Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bellsprout Lorem ipsum dolor sit amet, consectetur adipiscing elit. Weepinbell Lorem ipsum dolor sit amet, consectetur adipiscing elit. Victreebel Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tentacool Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tentacruel Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
        </div>
        <div class="col-md-4">
            <img src="https://vignette.wikia.nocookie.net/videojuego/images/5/5f/Stitch.png/revision/latest/scale-to-width-down/220" alt="me" />
        </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
          <a class="text-muted mr-3" href="link da sua rede social"><span class="zocial-facebook"></span></a>
          <a class="text-muted mr-3" href="link da sua rede social"><span class="zocial-twitter"></span></a>
          <a class="text-muted mr-3" href="link da sua rede social"><span class="zocial-linkedin"></span></a>
        </div>
        <div class="col-4 text-center">
          <a class="blog-header-logo text-dark" href="/">Seu Nome aqui</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <a class="text-muted mr-3" href="/">Portfolio</a>
          <a class="text-muted mr-3" href="<%= biography_path %>">Sobre mim</a>
        </div>
      </div>
    </header>

    <%= yield %>
    
    <footer class="footer bg-light py-4">
      <div class="container text-center">
        <p>Feito com <span class="entypo-heart"></span> por <a href="https://twitter.com/tecoara">Caroline</a>.</p>
        <p>
          <a href="#">Voltar para cima</a>
        </p>
      </div>
    </footer>

  </body>

</html>

app/views/projects/_form.html.erb
<%= form_for(project, :html => { :multipart => true }) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :project_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Ola! Eu sou a Caroline.</h1>
        <p class="lead text-muted">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti, nam, natus dignissimos dolores voluptates expedita facilis debitis blanditiis, perferendis sunt quidem asperiores saepe. Pariatur, obcaecati praesentium provident hic culpa alias! </p>
    </div>
</section>

<main class="container">

<p id="notice"><%= notice %></p>

<div class="album">
    <div class="container">
        <div class="row">
          <% @projects.each do |project| %>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                <%= image_tag(project.picture, :class => "card-img-top") if project.picture.present? %>
                <div class="card-body">
                    <h4><%= project.name %></h4>
                    <p class="card-text"><%= project.description %></p>
                    <div class="d-flex justify-content-between align-items-center">
                    <%= link_to 'Show', project, class: "btn btn-sm btn-outline-secondary" %>
                    </div>
                </div>
                </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

</main>

app/views/projects/new.html.erb
<main class="container">
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>
</main>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@project.picture, :width => 600) if @project.picture.present? %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>